obj = deck.obj
bin = deck.exe

CC = wcc
CFLAGS =
LC = wlink

$(bin): $(obj)
	$(LC) name $@ file { $(obj) }

.c.obj:
	$(CC) -fo=$@ $(CFLAGS) $<

clean: .symbolic
	del *.obj
	del $(bin)
	del errors
